stages:
  - build
  - package

.centos:
  tags: [linux, docker]
  image: git.imp.fu-berlin.de:5000/bioroboticslab/robofish/docker:centos

.windows:
  tags: [windows, docker]
  image: git.imp.fu-berlin.de:5000/bioroboticslab/robofish/docker:devel-windows
  before_script:
    - . $Profile.AllUsersAllHosts

.release: &release
  CMAKE_BUILD_TYPE: Release

.build: &build
  stage: build
  artifacts:
    paths:
      - vendor
      - build
    expire_in: 1 day
  script:
    - ./ci/prepare.py
    - ./ci/configure.py
    - ./ci/compile.py

.package: &package
  stage: package
  artifacts:
    paths:
      - build/*.tar.xz
      - build/*.msi
    expire_in: 1 week
  script:
    - ./ci/package.py

build centos:
  extends: .centos
  <<: *build
  variables:
    <<: [*release]

build windows:
  extends: .windows
  <<: *build
  variables:
    <<: [*release]

package centos:
  extends: .centos
  dependencies:
    - build centos
  <<: *package

package windows:
  extends: .windows
  dependencies:
    - build windows
  <<: *package
